language: python
python:
  - "2.7"
  - "3.2"
  - "3.4"
  - "3.5"
# command to install dependencies
install:
  - "pip install ."
  - "pip install -r test_requirements.txt"
# command to run tests
script: 
  - "cd tests"
  - "nosetests -vs test.py"
